# golangci-lint configuration for normal-form-app
# Simplified stable configuration

run:
  timeout: 5m
  tests: true
  go: "1.21"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      shadow:
        strict: false

  goimports:
    local-prefixes: github.com/octop162/normal-form-app-by-claude

  gofmt:
    simplify: true

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  funlen:
    lines: 100
    statements: 50

  lll:
    line-length: 120

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  unused:
    check-exported: false

  gosec:
    excludes:
      - G104 # Allow unchecked errors during development
    severity: medium
    confidence: medium

  revive:
    min-confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  staticcheck:
    checks: ["all", "-ST1000", "-ST1003"]

linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Additional stable linters
    - bodyclose
    - dupl
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-dirs:
    - vendor
    - node_modules
    - frontend
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - lll

    # Exclude long line rule for go:generate
    - linters:
        - lll
      source: "^//go:generate "

  max-issues-per-linter: 0
  max-same-issues: 0