name: Add Issues to Project

on:
  issues:
    types: [opened, reopened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/octop162/projects/7
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}